"""
DeepFlood 论坛签到插件（参考 NodeSeek 签到插件结构）
版本: 0.1.0
作者: anorl (generated by assistant)

说明：
- 参考 https://github.com/jxxghp/MoviePilot-Plugins 的第三方插件库开发说明
- 插件仓库保持目录结构：plugins/<plugin>/__init__.py
- 插件目录名必须为插件类名的小写：deepfloodsign
- requirements.txt 用于声明依赖，MoviePilot 安装时会自动安装

⚠️ DeepFlood 站点受 Cloudflare 防护影响较大，本插件提供 cloudscraper/curl_cffi 兜底。
⚠️ 不同站点签到接口路径可能不同，需要在插件配置中填写实际的签到 API 路径与请求方法。
"""

import time
import random
from datetime import datetime, timedelta
from typing import Any, List, Dict, Tuple, Optional

import pytz
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger

from app.core.config import settings
from app.plugins import _PluginBase
from app.log import logger
from app.schemas import NotificationType

# cloudscraper 作为 Cloudflare/WAF 备用方案
try:
    import cloudscraper
    HAS_CLOUDSCRAPER = True
except Exception:
    HAS_CLOUDSCRAPER = False

# curl_cffi (Chrome impersonate)
try:
    from curl_cffi import requests as curl_requests
    HAS_CURL_CFFI = True
except ImportError:
    HAS_CURL_CFFI = False

# requests 兜底
try:
    import requests
except Exception:
    requests = None


class deepfloodsign(_PluginBase):
    # 插件名称
    plugin_name = "DeepFlood论坛签到"
    # 插件描述
    plugin_desc = "自动完成DeepFlood论坛每日签到（参考NodeSeek签到插件范式），支持代理与失败兜底"
    # 插件图标
    plugin_icon = "https://raw.githubusercontent.com/anorl/MoviePilot-Plugins/main/icons/deepfloodsign.png"
    # 插件版本
    plugin_version = "0.1.0"
    # 插件作者
    plugin_author = "anorl"
    # 作者主页
    author_url = "https://github.com/anorl"
    # 插件配置项ID前缀
    plugin_config_prefix = "deepfloodsign_"
    # 加载顺序
    plugin_order = 1
    # 可使用的用户级别
    auth_level = 2

    # 配置
    _enabled = False
    _site_url = ""          # DeepFlood base url, e.g. https://www.deepflood.com
    _cookie = None          # 站点 Cookie
    _notify = False
    _onlyonce = False
    _cron = None
    _use_proxy = True
    _max_retries = 3
    _verify_ssl = False
    _min_delay = 5
    _max_delay = 12

    # 签到相关（可配置）
    _attendance_path = "/api/attendance"  # 默认按 NodeSeek；DeepFlood 需确认
    _attendance_method = "POST"           # POST/GET
    _attendance_random_param = "random"   # 可选：随机奖励参数名
    _random_choice = True

    _history_days = 30

    _scraper = None
    _scheduler: Optional[BackgroundScheduler] = None

    def init_plugin(self, config: dict = None):
        # 停止现有任务
        self.stop_service()
        logger.info("============= deepfloodsign 初始化 =============")

        try:
            if config:
                self._enabled = config.get("enabled")
                self._cookie = config.get("cookie")
                self._notify = config.get("notify")
                self._cron = config.get("cron")
                self._onlyonce = config.get("onlyonce")
                self._site_url = (config.get("site_url") or "").strip().rstrip('/')
                self._random_choice = config.get("random_choice", True)
                self._use_proxy = config.get("use_proxy", True)
                self._verify_ssl = config.get("verify_ssl", False)

                try:
                    self._max_retries = int(config.get("max_retries", 3))
                except Exception:
                    self._max_retries = 3

                try:
                    self._history_days = int(config.get("history_days", 30))
                except Exception:
                    self._history_days = 30

                try:
                    self._min_delay = int(config.get("min_delay", 5))
                except Exception:
                    self._min_delay = 5

                try:
                    self._max_delay = int(config.get("max_delay", 12))
                except Exception:
                    self._max_delay = 12

                # 可覆写 API path/method
                self._attendance_path = (config.get("attendance_path") or self._attendance_path).strip()
                self._attendance_method = (config.get("attendance_method") or self._attendance_method).strip().upper()

                logger.info(
                    f"配置: enabled={self._enabled}, notify={self._notify}, cron={self._cron}, site_url={self._site_url}, "
                    f"random_choice={self._random_choice}, history_days={self._history_days}, use_proxy={self._use_proxy}, "
                    f"max_retries={self._max_retries}, verify_ssl={self._verify_ssl}, min_delay={self._min_delay}, max_delay={self._max_delay}, "
                    f"attendance={self._attendance_method} {self._attendance_path}"
                )

                # 初始化 cloudscraper（可选）
                if HAS_CLOUDSCRAPER:
                    try:
                        self._scraper = cloudscraper.create_scraper(browser="chrome")
                    except Exception:
                        try:
                            self._scraper = cloudscraper.create_scraper()
                        except Exception as e2:
                            logger.warning(f"cloudscraper 初始化失败: {str(e2)}")
                            self._scraper = None

                    if self._scraper:
                        proxies = self._get_proxies()
                        if proxies:
                            self._scraper.proxies = proxies
                            logger.info(f"cloudscraper 初始化代理: {self._scraper.proxies}")
                        logger.info("cloudscraper 初始化成功")

            if self._onlyonce:
                logger.info("执行一次性签到")
                self._scheduler = BackgroundScheduler(timezone=settings.TZ)
                self._scheduler.add_job(func=self.sign, trigger='date',
                                        run_date=datetime.now(tz=pytz.timezone(settings.TZ)) + timedelta(seconds=3),
                                        name="DeepFlood论坛签到")
                self._onlyonce = False
                self.update_config({
                    "onlyonce": False,
                    "enabled": self._enabled,
                    "cookie": self._cookie,
                    "notify": self._notify,
                    "cron": self._cron,
                    "site_url": self._site_url,
                    "random_choice": self._random_choice,
                    "use_proxy": self._use_proxy,
                    "max_retries": self._max_retries,
                    "verify_ssl": self._verify_ssl,
                    "min_delay": self._min_delay,
                    "max_delay": self._max_delay,
                    "history_days": self._history_days,
                    "attendance_path": self._attendance_path,
                    "attendance_method": self._attendance_method,
                })

                if self._scheduler.get_jobs():
                    self._scheduler.print_jobs()
                    self._scheduler.start()

        except Exception as e:
            logger.error(f"deepfloodsign 初始化错误: {str(e)}", exc_info=True)

    def get_state(self) -> bool:
        return self._enabled

    def get_service(self) -> List[Dict[str, Any]]:
        if self._enabled and self._cron:
            logger.info(f"注册定时服务: {self._cron}")
            return [{
                "id": "deepfloodsign",
                "name": "DeepFlood论坛签到",
                "trigger": CronTrigger.from_crontab(self._cron),
                "func": self.sign,
                "kwargs": {}
            }]
        return []

    def _normalize_proxies(self, proxies_input):
        try:
            if not proxies_input:
                return None
            if isinstance(proxies_input, str):
                return {"http": proxies_input, "https": proxies_input}
            if isinstance(proxies_input, dict):
                http_url = proxies_input.get("http") or proxies_input.get("HTTP") or proxies_input.get("https") or proxies_input.get("HTTPS")
                https_url = proxies_input.get("https") or proxies_input.get("HTTPS") or proxies_input.get("http") or proxies_input.get("HTTP")
                if not http_url and not https_url:
                    return None
                return {"http": http_url or https_url, "https": https_url or http_url}
        except Exception as e:
            logger.warning(f"代理归一化失败，将忽略代理: {str(e)}")
        return None

    def _get_proxies(self):
        if not self._use_proxy:
            return None
        try:
            if hasattr(settings, 'PROXY') and settings.PROXY:
                return self._normalize_proxies(settings.PROXY)
        except Exception:
            pass
        return None

    def _wait_random_interval(self):
        try:
            min_delay = float(self._min_delay) if self._min_delay is not None else 5.0
            max_delay = float(self._max_delay) if self._max_delay is not None else 12.0
            if max_delay >= min_delay and min_delay > 0:
                delay = random.uniform(min_delay, max_delay)
                logger.info(f"请求前随机等待 {delay:.2f} 秒...")
                time.sleep(delay)
        except Exception:
            pass

    def _smart_post(self, url, headers=None, data=None, json_body=None, proxies=None, timeout=30):
        # 1) cloudscraper
        if HAS_CLOUDSCRAPER and self._scraper:
            try:
                if proxies:
                    self._scraper.proxies = self._normalize_proxies(proxies) or {}
                return self._scraper.post(url, headers=headers, data=data, json=json_body, timeout=timeout) if not self._verify_ssl else self._scraper.post(url, headers=headers, data=data, json=json_body, timeout=timeout, verify=True)
            except Exception as e:
                logger.warning(f"cloudscraper 请求失败，将回退：{str(e)}")

        # 2) curl_cffi
        if HAS_CURL_CFFI:
            session = curl_requests.Session(impersonate="chrome110")
            if proxies:
                session.proxies = self._normalize_proxies(proxies) or {}
            return session.post(url, headers=headers, data=data, json=json_body, timeout=timeout) if not self._verify_ssl else session.post(url, headers=headers, data=data, json=json_body, timeout=timeout, verify=True)

        # 3) requests
        if requests is None:
            raise Exception("requests not installed")
        norm = self._normalize_proxies(proxies)
        if self._verify_ssl:
            return requests.post(url, headers=headers, data=data, json=json_body, proxies=norm, timeout=timeout, verify=True)
        return requests.post(url, headers=headers, data=data, json=json_body, proxies=norm, timeout=timeout)

    def _smart_get(self, url, headers=None, proxies=None, timeout=30):
        # 1) cloudscraper
        if HAS_CLOUDSCRAPER and self._scraper:
            try:
                if proxies:
                    self._scraper.proxies = self._normalize_proxies(proxies) or {}
                return self._scraper.get(url, headers=headers, timeout=timeout) if not self._verify_ssl else self._scraper.get(url, headers=headers, timeout=timeout, verify=True)
            except Exception as e:
                logger.warning(f"cloudscraper GET 失败，将回退：{str(e)}")

        # 2) curl_cffi
        if HAS_CURL_CFFI:
            session = curl_requests.Session(impersonate="chrome110")
            if proxies:
                session.proxies = self._normalize_proxies(proxies) or {}
            return session.get(url, headers=headers, timeout=timeout) if not self._verify_ssl else session.get(url, headers=headers, timeout=timeout, verify=True)

        # 3) requests
        if requests is None:
            raise Exception("requests not installed")
        norm = self._normalize_proxies(proxies)
        if self._verify_ssl:
            return requests.get(url, headers=headers, proxies=norm, timeout=timeout, verify=True)
        return requests.get(url, headers=headers, proxies=norm, timeout=timeout)

    def _build_attendance_url(self) -> str:
        base = self._site_url.rstrip('/')
        path = self._attendance_path
        if not path.startswith('/'):
            path = '/' + path
        if self._attendance_random_param:
            rp = 'true' if self._random_choice else 'false'
            joiner = '&' if '?' in path else '?'
            return f"{base}{path}{joiner}{self._attendance_random_param}={rp}"
        return f"{base}{path}"

    def _run_api_sign(self) -> Dict[str, Any]:
        result = {"success": False, "signed": False, "already_signed": False, "message": ""}

        if not self._site_url:
            result["message"] = "未配置站点 URL"
            return result
        if not self._cookie:
            result["message"] = "未配置 Cookie"
            return result

        url = self._build_attendance_url()
        headers = {
            'Accept': '*/*',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Content-Type': 'application/json',
            'Origin': self._site_url,
            'Referer': f"{self._site_url}/board",
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
            'Cookie': self._cookie,
        }

        proxies = self._get_proxies()

        if self._attendance_method == 'GET':
            resp = self._smart_get(url=url, headers=headers, proxies=proxies, timeout=30)
        else:
            resp = self._smart_post(url=url, headers=headers, data=b'', json_body=None, proxies=proxies, timeout=30)

        status_code = getattr(resp, 'status_code', None)
        text = getattr(resp, 'text', '') or ''
        ct = ''
        try:
            ct = resp.headers.get('Content-Type') or resp.headers.get('content-type') or ''
        except Exception:
            pass

        data = None
        if 'application/json' in (ct or '').lower():
            try:
                data = resp.json()
            except Exception:
                data = None

        if isinstance(data, dict):
            msg = data.get('message', '')
            if data.get('success') is True:
                result.update({"success": True, "signed": True, "message": msg})
            elif ('已' in msg and '签到' in msg) or (data.get('signed') is True):
                result.update({"success": True, "already_signed": True, "message": msg or '今日已签到'})
            else:
                result.update({"message": msg or f"未知响应({status_code})"})
        else:
            if any(k in text for k in ['已完成签到', '今日已签到', '签到成功']):
                result.update({"success": True, "signed": True, "message": text[:80]})
            elif any(k in text for k in ['请登录', '登录', '注册']):
                result.update({"message": "未登录或Cookie失效"})
            else:
                result.update({"message": f"非JSON响应({status_code})"})

        return result

    def sign(self):
        logger.info("============= 开始 DeepFlood 签到 =============")

        if not self._cookie:
            sign_dict = {"date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'), "status": "签到失败: 未配置Cookie"}
            self._save_sign_history(sign_dict)
            if self._notify:
                self.post_message(mtype=NotificationType.SiteMessage, title="【DeepFlood论坛签到失败】", text="未配置Cookie，请在设置中添加Cookie")
            return sign_dict

        if not self._site_url:
            sign_dict = {"date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'), "status": "签到失败: 未配置站点URL"}
            self._save_sign_history(sign_dict)
            if self._notify:
                self.post_message(mtype=NotificationType.SiteMessage, title="【DeepFlood论坛签到失败】", text="未配置站点URL，请在设置中填写")
            return sign_dict

        self._wait_random_interval()

        last_exc = None
        for attempt in range(1, int(self._max_retries) + 1):
            try:
                result = self._run_api_sign()
                break
            except Exception as e:
                last_exc = e
                logger.warning(f"签到请求异常，准备重试({attempt}/{self._max_retries}): {str(e)}")
                time.sleep(2)
        else:
            result = {"success": False, "message": f"重试后仍失败: {last_exc}"}

        if result.get('success') and result.get('signed'):
            status = f"签到成功: {result.get('message','')}"
        elif result.get('success') and result.get('already_signed'):
            status = f"今日已签到: {result.get('message','')}"
        else:
            status = f"签到失败: {result.get('message','未知错误')}"

        sign_dict = {"date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'), "status": status}
        self._save_sign_history(sign_dict)

        if self._notify:
            title = "【✅ DeepFlood论坛签到】" if (result.get('success') and (result.get('signed') or result.get('already_signed'))) else "【❌ DeepFlood论坛签到失败】"
            self.post_message(mtype=NotificationType.SiteMessage, title=title, text=f"{status}\n⏱️ {sign_dict['date']}")

        return sign_dict

    def _save_sign_history(self, sign_data):
        try:
            history = self.get_data('sign_history') or []
            if "date" not in sign_data:
                sign_data["date"] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            history.append(sign_data)

            retention_days = int(self._history_days) if self._history_days is not None else 30
            now = datetime.now()
            valid_history = []
            for record in history:
                try:
                    record_date = datetime.strptime(record["date"], '%Y-%m-%d %H:%M:%S')
                    if (now - record_date).days < retention_days:
                        valid_history.append(record)
                except Exception:
                    record["date"] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                    valid_history.append(record)

            self.save_data(key="sign_history", value=valid_history)
        except Exception as e:
            logger.error(f"保存签到历史记录失败: {str(e)}", exc_info=True)

    def stop_service(self):
        try:
            if self._scheduler:
                self._scheduler.remove_all_jobs()
                if self._scheduler.running:
                    self._scheduler.shutdown()
                self._scheduler = None
        except Exception:
            pass

    @staticmethod
    def get_form() -> Tuple[List[dict], Dict[str, Any]]:
        curl_cffi_status = "✅ 已安装" if HAS_CURL_CFFI else "❌ 未安装"
        cloudscraper_status = "✅ 已启用" if HAS_CLOUDSCRAPER else "❌ 未启用"

        return [
            {
                'component': 'VForm',
                'content': [
                    {
                        'component': 'VRow',
                        'content': [
                            {
                                'component': 'VCol',
                                'props': {'cols': 12, 'md': 3},
                                'content': [{'component': 'VSwitch', 'props': {'model': 'enabled', 'label': '启用插件'}}]
                            },
                            {
                                'component': 'VCol',
                                'props': {'cols': 12, 'md': 3},
                                'content': [{'component': 'VSwitch', 'props': {'model': 'notify', 'label': '开启通知'}}]
                            },
                            {
                                'component': 'VCol',
                                'props': {'cols': 12, 'md': 3},
                                'content': [{'component': 'VSwitch', 'props': {'model': 'random_choice', 'label': '随机奖励(如支持)'}}]
                            },
                            {
                                'component': 'VCol',
                                'props': {'cols': 12, 'md': 3},
                                'content': [{'component': 'VSwitch', 'props': {'model': 'onlyonce', 'label': '立即运行一次'}}]
                            },
                        ]
                    },
                    {
                        'component': 'VRow',
                        'content': [
                            {
                                'component': 'VCol',
                                'props': {'cols': 12, 'md': 6},
                                'content': [{'component': 'VTextField', 'props': {'model': 'site_url', 'label': 'DeepFlood站点URL', 'placeholder': 'https://www.deepflood.com'}}]
                            },
                            {
                                'component': 'VCol',
                                'props': {'cols': 12, 'md': 6},
                                'content': [{'component': 'VTextField', 'props': {'model': 'cron', 'label': '定时任务(cron)', 'placeholder': '0 9 * * * (每天9点)'}}]
                            },
                        ]
                    },
                    {
                        'component': 'VRow',
                        'content': [
                            {
                                'component': 'VCol',
                                'props': {'cols': 12},
                                'content': [{'component': 'VTextField', 'props': {'model': 'cookie', 'label': '站点Cookie', 'placeholder': '请输入站点Cookie值'}}]
                            }
                        ]
                    },
                    {
                        'component': 'VRow',
                        'content': [
                            {
                                'component': 'VCol',
                                'props': {'cols': 12, 'md': 6},
                                'content': [{'component': 'VTextField', 'props': {'model': 'attendance_path', 'label': '签到API路径', 'placeholder': '/api/attendance 或 /attendance.php 等'}}]
                            },
                            {
                                'component': 'VCol',
                                'props': {'cols': 12, 'md': 6},
                                'content': [{'component': 'VSelect', 'props': {'model': 'attendance_method', 'label': '签到请求方法', 'items': [{'title': 'POST', 'value': 'POST'}, {'title': 'GET', 'value': 'GET'}]}}]
                            },
                        ]
                    },
                    {
                        'component': 'VRow',
                        'content': [
                            {
                                'component': 'VCol',
                                'props': {'cols': 12},
                                'content': [{'component': 'VAlert', 'props': {'type': 'info', 'variant': 'tonal', 'text': f"依赖状态：curl_cffi={curl_cffi_status}，cloudscraper={cloudscraper_status}。\n\n如 DeepFlood 的签到接口不是 /api/attendance，请在上方配置实际路径与方法。"}}]
                            }
                        ]
                    },
                ]
            }
        ], {
            "enabled": False,
            "notify": False,
            "onlyonce": False,
            "cron": "0 9 * * *",
            "cookie": "",
            "site_url": "https://www.deepflood.com",
            "random_choice": True,
            "use_proxy": True,
            "max_retries": 3,
            "verify_ssl": False,
            "min_delay": 5,
            "max_delay": 12,
            "history_days": 30,
            "attendance_path": "/api/attendance",
            "attendance_method": "POST"
        }
