"""
DeepFlood 论坛签到插件（参考 NodeSeek 签到插件结构）
版本: 0.1.9
作者: anorl (generated by assistant)

说明：
- 参考 https://github.com/jxxghp/MoviePilot-Plugins 的第三方插件库开发说明
- 插件仓库保持目录结构：plugins/<plugin>/__init__.py
- 插件目录名必须为插件类名的小写：deepfloodsign
- requirements.txt 用于声明依赖，MoviePilot 安装时会自动安装

⚠️ DeepFlood 站点受 Cloudflare 防护影响较大，本插件提供 cloudscraper/curl_cffi 兜底。
⚠️ 不同站点签到接口路径可能不同，需要在插件配置中填写实际的签到 API 路径与请求方法。
"""

import re
import time
import random
from datetime import datetime, timedelta
from typing import Any, List, Dict, Tuple, Optional

import pytz
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger

from app.core.config import settings
from app.plugins import _PluginBase
from app.log import logger
from app.schemas import NotificationType

# cloudscraper 作为 Cloudflare/WAF 备用方案
try:
    import cloudscraper
    HAS_CLOUDSCRAPER = True
except Exception:
    HAS_CLOUDSCRAPER = False

# curl_cffi (Chrome impersonate)
try:
    from curl_cffi import requests as curl_requests
    HAS_CURL_CFFI = True
except ImportError:
    HAS_CURL_CFFI = False

# requests 兜底
try:
    import requests
except Exception:
    requests = None


class deepfloodsign(_PluginBase):
    # 插件名称
    plugin_name = "DeepFlood论坛签到"
    # 插件描述
    plugin_desc = "自动完成DeepFlood论坛每日签到（参考NodeSeek签到插件范式），支持代理与失败兜底"
    # 插件图标
    plugin_icon = "https://raw.githubusercontent.com/anorl/MoviePilot-Plugins/main/icons/deepfloodsign.png"
    # 插件版本
    plugin_version = "0.1.9"
    # 插件作者
    plugin_author = "anorl"
    # 作者主页
    author_url = "https://github.com/anorl"
    # 插件配置项ID前缀
    plugin_config_prefix = "deepfloodsign_"
    # 加载顺序
    plugin_order = 1
    # 可使用的用户级别
    auth_level = 2

    # 配置
    _enabled = False
    _site_url = ""          # DeepFlood base url, e.g. https://www.deepflood.com
    _cookie = None          # 站点 Cookie
    _notify = False
    _onlyonce = False
    _cron = None
    _use_proxy = True
    _max_retries = 3
    _verify_ssl = False
    _min_delay = 5
    _max_delay = 12

    # 签到相关（可配置）
    _attendance_path = "/api/attendance"  # 默认按 NodeSeek；DeepFlood 需确认
    _attendance_method = "POST"           # POST/GET
    _attendance_random_param = "random"   # 可选：随机奖励参数名
    _attendance_record_path = "/api/attendance/board?page=1"  # 用于获取奖励/排名
    _user_info_path = "/api/account/getInfo/{member_id}?readme=1"  # 用于获取用户信息
    _member_id = ""  # 站点用户ID（用于用户信息查询）
    _random_choice = True

    _history_days = 30

    _scraper = None
    _scheduler: Optional[BackgroundScheduler] = None

    def init_plugin(self, config: dict = None):
        # 停止现有任务
        self.stop_service()
        logger.info("============= deepfloodsign 初始化 =============")

        try:
            if config:
                self._enabled = config.get("enabled")
                self._cookie = config.get("cookie")
                self._notify = config.get("notify")
                self._cron = config.get("cron")
                self._onlyonce = config.get("onlyonce")
                self._site_url = (config.get("site_url") or "").strip().rstrip('/')
                self._random_choice = config.get("random_choice", True)
                self._use_proxy = config.get("use_proxy", True)
                self._verify_ssl = config.get("verify_ssl", False)

                try:
                    self._max_retries = int(config.get("max_retries", 3))
                except Exception:
                    self._max_retries = 3

                try:
                    self._history_days = int(config.get("history_days", 30))
                except Exception:
                    self._history_days = 30

                try:
                    self._min_delay = int(config.get("min_delay", 5))
                except Exception:
                    self._min_delay = 5

                try:
                    self._max_delay = int(config.get("max_delay", 12))
                except Exception:
                    self._max_delay = 12

                # 可覆写 API path/method
                self._attendance_path = (config.get("attendance_path") or self._attendance_path).strip()
                self._attendance_method = (config.get("attendance_method") or self._attendance_method).strip().upper()
                self._attendance_record_path = (config.get("attendance_record_path") or self._attendance_record_path).strip()
                self._user_info_path = (config.get("user_info_path") or self._user_info_path).strip()
                self._member_id = (config.get("member_id") or "").strip()

                logger.info(
                    f"配置: enabled={self._enabled}, notify={self._notify}, cron={self._cron}, site_url={self._site_url}, "
                    f"random_choice={self._random_choice}, history_days={self._history_days}, use_proxy={self._use_proxy}, "
                    f"max_retries={self._max_retries}, verify_ssl={self._verify_ssl}, min_delay={self._min_delay}, max_delay={self._max_delay}, "
                    f"attendance={self._attendance_method} {self._attendance_path}, "
                    f"attendance_record_path={self._attendance_record_path}, user_info_path={self._user_info_path}, member_id={self._member_id or '未设置'}"
                )

                # 初始化 cloudscraper（可选）
                if HAS_CLOUDSCRAPER:
                    try:
                        self._scraper = cloudscraper.create_scraper(browser="chrome")
                    except Exception:
                        try:
                            self._scraper = cloudscraper.create_scraper()
                        except Exception as e2:
                            logger.warning(f"cloudscraper 初始化失败: {str(e2)}")
                            self._scraper = None

                    if self._scraper:
                        proxies = self._get_proxies()
                        if proxies:
                            self._scraper.proxies = proxies
                            logger.info(f"cloudscraper 初始化代理: {self._scraper.proxies}")
                        logger.info("cloudscraper 初始化成功")

            if self._onlyonce:
                logger.info("执行一次性签到")
                self._scheduler = BackgroundScheduler(timezone=settings.TZ)
                self._scheduler.add_job(func=self.sign, trigger='date',
                                        run_date=datetime.now(tz=pytz.timezone(settings.TZ)) + timedelta(seconds=3),
                                        name="DeepFlood论坛签到")
                self._onlyonce = False
                self.update_config({
                    "onlyonce": False,
                    "enabled": self._enabled,
                    "cookie": self._cookie,
                    "notify": self._notify,
                    "cron": self._cron,
                    "site_url": self._site_url,
                    "random_choice": self._random_choice,
                    "use_proxy": self._use_proxy,
                    "max_retries": self._max_retries,
                    "verify_ssl": self._verify_ssl,
                    "min_delay": self._min_delay,
                    "max_delay": self._max_delay,
                    "history_days": self._history_days,
                    "attendance_path": self._attendance_path,
                    "attendance_method": self._attendance_method,
                    "attendance_record_path": self._attendance_record_path,
                    "user_info_path": self._user_info_path,
                    "member_id": self._member_id,
                })

                if self._scheduler.get_jobs():
                    self._scheduler.print_jobs()
                    self._scheduler.start()

        except Exception as e:
            logger.error(f"deepfloodsign 初始化错误: {str(e)}", exc_info=True)

    def get_state(self) -> bool:
        return self._enabled

    def get_service(self) -> List[Dict[str, Any]]:
        if self._enabled and self._cron:
            logger.info(f"注册定时服务: {self._cron}")
            return [{
                "id": "deepfloodsign",
                "name": "DeepFlood论坛签到",
                "trigger": CronTrigger.from_crontab(self._cron),
                "func": self.sign,
                "kwargs": {}
            }]
        return []

    def _normalize_proxies(self, proxies_input):
        try:
            if not proxies_input:
                return None
            if isinstance(proxies_input, str):
                return {"http": proxies_input, "https": proxies_input}
            if isinstance(proxies_input, dict):
                http_url = proxies_input.get("http") or proxies_input.get("HTTP") or proxies_input.get("https") or proxies_input.get("HTTPS")
                https_url = proxies_input.get("https") or proxies_input.get("HTTPS") or proxies_input.get("http") or proxies_input.get("HTTP")
                if not http_url and not https_url:
                    return None
                return {"http": http_url or https_url, "https": https_url or http_url}
        except Exception as e:
            logger.warning(f"代理归一化失败，将忽略代理: {str(e)}")
        return None

    def _get_proxies(self):
        if not self._use_proxy:
            return None
        try:
            if hasattr(settings, 'PROXY') and settings.PROXY:
                return self._normalize_proxies(settings.PROXY)
        except Exception:
            pass
        return None

    def _wait_random_interval(self):
        try:
            min_delay = float(self._min_delay) if self._min_delay is not None else 5.0
            max_delay = float(self._max_delay) if self._max_delay is not None else 12.0
            if max_delay >= min_delay and min_delay > 0:
                delay = random.uniform(min_delay, max_delay)
                logger.info(f"请求前随机等待 {delay:.2f} 秒...")
                time.sleep(delay)
        except Exception:
            pass

    def _smart_post(self, url, headers=None, data=None, json_body=None, proxies=None, timeout=30):
        # 1) cloudscraper
        if HAS_CLOUDSCRAPER and self._scraper:
            try:
                if proxies:
                    self._scraper.proxies = self._normalize_proxies(proxies) or {}
                return self._scraper.post(url, headers=headers, data=data, json=json_body, timeout=timeout) if not self._verify_ssl else self._scraper.post(url, headers=headers, data=data, json=json_body, timeout=timeout, verify=True)
            except Exception as e:
                logger.warning(f"cloudscraper 请求失败，将回退：{str(e)}")

        # 2) curl_cffi
        if HAS_CURL_CFFI:
            session = curl_requests.Session(impersonate="chrome110")
            if proxies:
                session.proxies = self._normalize_proxies(proxies) or {}
            return session.post(url, headers=headers, data=data, json=json_body, timeout=timeout) if not self._verify_ssl else session.post(url, headers=headers, data=data, json=json_body, timeout=timeout, verify=True)

        # 3) requests
        if requests is None:
            raise Exception("requests not installed")
        norm = self._normalize_proxies(proxies)
        if self._verify_ssl:
            return requests.post(url, headers=headers, data=data, json=json_body, proxies=norm, timeout=timeout, verify=True)
        return requests.post(url, headers=headers, data=data, json=json_body, proxies=norm, timeout=timeout)

    def _smart_get(self, url, headers=None, proxies=None, timeout=30):
        # 1) cloudscraper
        if HAS_CLOUDSCRAPER and self._scraper:
            try:
                if proxies:
                    self._scraper.proxies = self._normalize_proxies(proxies) or {}
                return self._scraper.get(url, headers=headers, timeout=timeout) if not self._verify_ssl else self._scraper.get(url, headers=headers, timeout=timeout, verify=True)
            except Exception as e:
                logger.warning(f"cloudscraper GET 失败，将回退：{str(e)}")

        # 2) curl_cffi
        if HAS_CURL_CFFI:
            session = curl_requests.Session(impersonate="chrome110")
            if proxies:
                session.proxies = self._normalize_proxies(proxies) or {}
            return session.get(url, headers=headers, timeout=timeout) if not self._verify_ssl else session.get(url, headers=headers, timeout=timeout, verify=True)

        # 3) requests
        if requests is None:
            raise Exception("requests not installed")
        norm = self._normalize_proxies(proxies)
        if self._verify_ssl:
            return requests.get(url, headers=headers, proxies=norm, timeout=timeout, verify=True)
        return requests.get(url, headers=headers, proxies=norm, timeout=timeout)

    def _build_attendance_url(self) -> str:
        base = self._site_url.rstrip('/')
        path = self._attendance_path
        if not path.startswith('/'):
            path = '/' + path
        if self._attendance_random_param:
            rp = 'true' if self._random_choice else 'false'
            joiner = '&' if '?' in path else '?'
            return f"{base}{path}{joiner}{self._attendance_random_param}={rp}"
        return f"{base}{path}"

    def _run_api_sign(self) -> Dict[str, Any]:
        """尽量复用 nodeseeksign 的签到逻辑：API优先 + 非JSON兜底 + cloudscraper预热重试"""
        try:
            result = {"success": False, "signed": False, "already_signed": False, "message": "", "gain": None}

            if not self._site_url:
                result["message"] = "未配置站点 URL"
                return result
            if not self._cookie:
                result["message"] = "未配置 Cookie"
                return result

            url = self._build_attendance_url()
            origin = self._site_url
            referer = f"{self._site_url}/board"

            headers = {
                'Accept': '*/*',
                'Accept-Encoding': 'gzip, deflate, br, zstd',
                'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
                'Content-Length': '0',
                'Content-Type': 'application/json',
                'Origin': origin,
                'Referer': referer,
                'Sec-Fetch-Dest': 'empty',
                'Sec-Fetch-Mode': 'cors',
                'Sec-Fetch-Site': 'same-origin',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
                'Cookie': self._cookie,
            }

            proxies = self._get_proxies()

            # 主请求
            if self._attendance_method == 'GET':
                response = self._smart_get(url=url, headers=headers, proxies=proxies, timeout=30)
            else:
                response = self._smart_post(url=url, headers=headers, data=b'', json_body=None, proxies=proxies, timeout=30)

            try:
                logger.info(f"签到响应状态码: {getattr(response, 'status_code', None)}")
                ct = response.headers.get('Content-Type') or response.headers.get('content-type')
                if ct:
                    logger.info(f"签到响应Content-Type: {ct}")
            except Exception:
                pass

            # 优先 JSON
            try:
                data = response.json()
                msg = data.get('message', '') if isinstance(data, dict) else ''

                gain = self._extract_gain(data, msg)
                if isinstance(data, dict) and data.get('success') is True:
                    result.update({"success": True, "signed": True, "message": msg})
                elif msg and ("鸡腿" in msg or ("签到" in msg and ("成功" in msg or "完成" in msg))):
                    result.update({"success": True, "signed": True, "message": msg})
                elif msg and ("已完成签到" in msg or "今日已签到" in msg):
                    result.update({"success": True, "already_signed": True, "message": msg})
                elif msg == "USER NOT FOUND" or (isinstance(data, dict) and data.get('status') == 404):
                    result.update({"message": "Cookie已失效，请更新"})
                else:
                    result.update({"message": msg or f"未知响应: {getattr(response, 'status_code', None)}"})
                if gain is not None:
                    result["gain"] = gain
                return result

            except Exception:
                # 非 JSON：记录片段 + cloudscraper 预热重试（复用 nodeseeksign 思路）
                text = getattr(response, 'text', '') or ''
                snippet = text[:400] if len(text) > 400 else text
                logger.warning(f"非JSON签到响应文本片段: {snippet}")
                try:
                    self.save_data('last_sign_response', {
                        'status_code': getattr(response, 'status_code', None),
                        'content_type': getattr(getattr(response, 'headers', {}), 'get', lambda *_: '')('Content-Type', ''),
                        'text_snippet': snippet
                    })
                except Exception:
                    pass

                try:
                    warm = self._scraper_warmup_and_attach_user_cookie()
                    if warm and self._attendance_method != 'GET':
                        logger.info("尝试 cloudscraper 预热后携带用户Cookie再次POST")
                        headers_retry = dict(headers)
                        headers_retry.pop('Cookie', None)
                        resp_retry = warm.post(url, headers=headers_retry, timeout=30)
                        ct_retry = resp_retry.headers.get('Content-Type', '')
                        if 'application/json' in (ct_retry or '').lower():
                            data = resp_retry.json()
                            msg = data.get('message', '') if isinstance(data, dict) else ''
                            gain = self._extract_gain(data, msg)
                            if isinstance(data, dict) and data.get('success') is True:
                                result.update({"success": True, "signed": True, "message": msg})
                                if gain is not None:
                                    result["gain"] = gain
                                return result
                            elif msg and ("已完成签到" in msg or "今日已签到" in msg):
                                result.update({"success": True, "already_signed": True, "message": msg})
                                if gain is not None:
                                    result["gain"] = gain
                                return result
                except Exception as e2:
                    logger.warning(f"预热+重试失败: {str(e2)}")

                if any(k in text for k in ["鸡腿", "签到成功", "签到完成", "已完成签到"]):
                    result.update({"success": True, "signed": True, "message": text[:80]})
                elif any(k in text for k in ["今日已签到", "已签到"]):
                    result.update({"success": True, "already_signed": True, "message": text[:80]})
                elif "Cannot GET" in text and "attendance" in text:
                    result.update({"message": "服务端拒绝GET，需要POST；可能被WAF拦截"})
                elif any(k in text for k in ["登录", "注册", "陌生人"]):
                    result.update({"message": "未登录或Cookie失效，返回登录页"})
                else:
                    result.update({"message": f"非JSON响应({getattr(response, 'status_code', None)})"})

                return result

        except Exception as e:
            logger.error(f"API签到出错: {str(e)}", exc_info=True)
            return {"success": False, "message": f"API签到出错: {str(e)}"}

    @staticmethod
    def _extract_gain(data: Any, message: str = "") -> Optional[int]:
        # 从常见 JSON 字段中提取奖励值
        if isinstance(data, dict):
            for key in ["gain", "reward", "amount", "coin", "bonus"]:
                value = data.get(key)
                if isinstance(value, (int, float)) and value >= 0:
                    return int(value)
            nested = data.get("data")
            if isinstance(nested, dict):
                for key in ["gain", "reward", "amount", "coin", "bonus"]:
                    value = nested.get(key)
                    if isinstance(value, (int, float)) and value >= 0:
                        return int(value)

        # 从消息中提取“xx鸡腿”
        if message:
            matched = re.search(r"(\d+)\s*鸡腿", message)
            if matched:
                try:
                    return int(matched.group(1))
                except Exception:
                    return None
        return None

    def _build_common_headers(self, referer_path: str = "/board", with_cookie: bool = True) -> Dict[str, str]:
        origin = self._site_url
        referer_path = referer_path or "/board"
        if not referer_path.startswith("/"):
            referer_path = "/" + referer_path
        headers = {
            "Accept": "*/*",
            "Accept-Encoding": "gzip, deflate, br, zstd",
            "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
            "Origin": origin,
            "Referer": f"{origin}{referer_path}",
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
        }
        if with_cookie and self._cookie:
            headers["Cookie"] = self._cookie
        return headers

    def _build_site_url(self, path: str) -> str:
        path = (path or "").strip()
        if path.startswith("http://") or path.startswith("https://"):
            return path
        if not path.startswith("/"):
            path = "/" + path
        return f"{self._site_url.rstrip('/')}{path}"

    def _fetch_user_info(self) -> Dict[str, Any]:
        if not self._site_url or not self._cookie or not self._member_id or not self._user_info_path:
            return {}
        try:
            path = self._user_info_path
            if "{member_id}" in path:
                path = path.format(member_id=self._member_id)
            url = self._build_site_url(path)
            headers = self._build_common_headers(referer_path=f"/space/{self._member_id}", with_cookie=True)
            resp = self._smart_get(url=url, headers=headers, proxies=self._get_proxies(), timeout=30)
            data = {}
            try:
                data = resp.json()
            except Exception:
                return {}

            detail = {}
            if isinstance(data, dict):
                if isinstance(data.get("detail"), dict):
                    detail = data.get("detail")
                elif isinstance(data.get("data"), dict):
                    detail = data.get("data")
                elif isinstance(data.get("user"), dict):
                    detail = data.get("user")
                else:
                    detail = data

            if not isinstance(detail, dict):
                return {}

            normalized = {
                "member_name": detail.get("member_name") or detail.get("name") or detail.get("username") or detail.get("nick_name"),
                "rank": detail.get("rank") or detail.get("level") or detail.get("user_level"),
                "coin": detail.get("coin") or detail.get("bonus") or detail.get("chicken_leg"),
            }
            self.save_data("last_user_info", normalized)
            return normalized
        except Exception as e:
            logger.warning(f"获取用户信息失败: {str(e)}")
            return {}

    def _fetch_attendance_record(self) -> Dict[str, Any]:
        if not self._site_url or not self._cookie or not self._attendance_record_path:
            return {}
        try:
            url = self._build_site_url(self._attendance_record_path)
            headers = self._build_common_headers(referer_path="/board", with_cookie=True)
            resp = self._smart_get(url=url, headers=headers, proxies=self._get_proxies(), timeout=30)
            try:
                data = resp.json()
            except Exception:
                return {}

            record = {}
            if isinstance(data, dict):
                if isinstance(data.get("record"), dict):
                    record = data.get("record")
                elif isinstance(data.get("data"), dict) and isinstance(data.get("data").get("record"), dict):
                    record = data.get("data").get("record")
                elif isinstance(data.get("data"), list) and data.get("data"):
                    first = data.get("data")[0]
                    record = first if isinstance(first, dict) else {}

            if not isinstance(record, dict):
                return {}

            normalized = {
                "gain": record.get("gain") or record.get("reward") or record.get("amount"),
                "rank": record.get("rank") or data.get("order"),
                "total_signers": record.get("total_signers") or data.get("total"),
                "created_at": record.get("created_at") or record.get("create_time"),
            }
            self.save_data("last_attendance_record", normalized)
            return normalized
        except Exception as e:
            logger.warning(f"获取签到记录失败: {str(e)}")
            return {}

    def _send_sign_notification(
        self,
        sign_dict: Dict[str, Any],
        result: Dict[str, Any],
        user_info: Optional[Dict[str, Any]] = None,
        attendance_record: Optional[Dict[str, Any]] = None,
    ):
        if not self._notify:
            return

        status = sign_dict.get("status", "未知")
        sign_time = sign_dict.get("date", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        ok = bool(result.get("success") and (result.get("signed") or result.get("already_signed")))
        title = "【✅ DeepFlood论坛签到成功】" if ok else "【❌ DeepFlood论坛签到失败】"

        user_info = user_info or {}
        attendance_record = attendance_record or {}
        gain = result.get("gain") if result.get("gain") is not None else attendance_record.get("gain")
        rank = attendance_record.get("rank")
        total_signers = attendance_record.get("total_signers")

        lines = [
            "📢 执行结果",
            "━━━━━━━━━━",
            f"🕐 时间：{sign_time}",
            f"✨ 状态：{status}",
        ]

        member_name = user_info.get("member_name")
        user_rank = user_info.get("rank")
        user_coin = user_info.get("coin")
        if member_name or user_rank or user_coin:
            lines.append(
                f"👤 用户：{member_name or '未知'}  等级：{user_rank or '未知'}  鸡腿：{user_coin if user_coin is not None else '未知'}"
            )

        if gain is not None:
            lines.append(f"🎁 获得：{gain}个鸡腿")
        if rank:
            rank_text = f"🏆 排名：第{rank}名"
            if total_signers:
                rank_text += f" (共{total_signers}人)"
            lines.append(rank_text)
        elif total_signers:
            lines.append(f"📊 今日共{total_signers}人签到")

        lines.append("━━━━━━━━━━")
        self.post_message(mtype=NotificationType.SiteMessage, title=title, text="\n".join(lines))

    def _scraper_warmup_and_attach_user_cookie(self):
        """参考 nodeseeksign：先 GET /board 预热，再把用户 Cookie 拆分塞进 cloudscraper cookie jar。"""
        try:
            if not (HAS_CLOUDSCRAPER and self._scraper):
                return None

            proxies = self._get_proxies()
            if proxies:
                self._scraper.proxies = self._normalize_proxies(proxies) or {}

            self._scraper.get(f"{self._site_url}/board", timeout=30)

            # 尝试推断 domain
            domain = None
            try:
                from urllib.parse import urlparse
                domain = urlparse(self._site_url).hostname
            except Exception:
                domain = None

            base = self._cookie or ''
            for part in base.split(';'):
                kv = part.strip().split('=', 1)
                if len(kv) == 2:
                    name, value = kv[0].strip(), kv[1].strip()
                    if name and value:
                        if domain:
                            self._scraper.cookies.set(name, value, domain=domain)
                        else:
                            self._scraper.cookies.set(name, value)
            return self._scraper
        except Exception as e:
            logger.warning(f"cloudscraper 预热失败: {str(e)}")
            return None
    def sign(self):
        logger.info("============= 开始 DeepFlood 签到 =============")

        if not self._cookie:
            sign_dict = {"date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'), "status": "签到失败: 未配置Cookie"}
            self._save_sign_history(sign_dict)
            if self._notify:
                self.post_message(mtype=NotificationType.SiteMessage, title="【DeepFlood论坛签到失败】", text="未配置Cookie，请在设置中添加Cookie")
            return sign_dict

        if not self._site_url:
            sign_dict = {"date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'), "status": "签到失败: 未配置站点URL"}
            self._save_sign_history(sign_dict)
            if self._notify:
                self.post_message(mtype=NotificationType.SiteMessage, title="【DeepFlood论坛签到失败】", text="未配置站点URL，请在设置中填写")
            return sign_dict

        self._wait_random_interval()

        last_exc = None
        for attempt in range(1, int(self._max_retries) + 1):
            try:
                result = self._run_api_sign()
                break
            except Exception as e:
                last_exc = e
                logger.warning(f"签到请求异常，准备重试({attempt}/{self._max_retries}): {str(e)}")
                time.sleep(2)
        else:
            result = {"success": False, "message": f"重试后仍失败: {last_exc}"}

        user_info = {}
        attendance_record = {}
        try:
            if self._member_id:
                user_info = self._fetch_user_info()
        except Exception:
            user_info = {}
        try:
            attendance_record = self._fetch_attendance_record()
            if attendance_record.get("gain") is not None and result.get("gain") is None:
                result["gain"] = attendance_record.get("gain")
        except Exception:
            attendance_record = {}

        if result.get('success') and result.get('signed'):
            status = f"签到成功: {result.get('message','')}"
        elif result.get('success') and result.get('already_signed'):
            status = f"今日已签到: {result.get('message','')}"
        else:
            status = f"签到失败: {result.get('message','未知错误')}"

        sign_dict = {"date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'), "status": status}
        if result.get("gain") is not None:
            sign_dict["gain"] = result.get("gain")
        if attendance_record.get("rank") is not None:
            sign_dict["rank"] = attendance_record.get("rank")
        if attendance_record.get("total_signers") is not None:
            sign_dict["total_signers"] = attendance_record.get("total_signers")
        self._save_sign_history(sign_dict)

        if self._notify:
            self._send_sign_notification(
                sign_dict=sign_dict,
                result=result,
                user_info=user_info,
                attendance_record=attendance_record,
            )

        return sign_dict

    def _save_sign_history(self, sign_data):
        try:
            history = self.get_data('sign_history') or []
            if "date" not in sign_data:
                sign_data["date"] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            history.append(sign_data)

            retention_days = int(self._history_days) if self._history_days is not None else 30
            now = datetime.now()
            valid_history = []
            for record in history:
                try:
                    record_date = datetime.strptime(record["date"], '%Y-%m-%d %H:%M:%S')
                    if (now - record_date).days < retention_days:
                        valid_history.append(record)
                except Exception:
                    record["date"] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                    valid_history.append(record)

            self.save_data(key="sign_history", value=valid_history)
        except Exception as e:
            logger.error(f"保存签到历史记录失败: {str(e)}", exc_info=True)

    def stop_service(self):
        try:
            if self._scheduler:
                self._scheduler.remove_all_jobs()
                if self._scheduler.running:
                    self._scheduler.shutdown()
                self._scheduler = None
        except Exception:
            pass

    def get_form(self) -> Tuple[List[dict], Dict[str, Any]]:
        """返回插件配置表单（Vuetify JSON）。

        说明：MoviePilot v2 某些情况下若表单渲染异常，会表现为"此插件没有可配置项"。
        这里显式记录日志，并在异常时返回一个错误提示表单，方便定位问题。
        """
        try:
            logger.info("[deepfloodsign] get_form called")

            curl_cffi_status = "✅ 已安装" if HAS_CURL_CFFI else "❌ 未安装"
            cloudscraper_status = "✅ 已启用" if HAS_CLOUDSCRAPER else "❌ 未启用"

            form = [
                {
                    'component': 'VForm',
                    'content': [
                        {
                            'component': 'VRow',
                            'content': [
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 3},
                                    'content': [{'component': 'VSwitch', 'props': {'model': 'enabled', 'label': '启用插件'}}]
                                },
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 3},
                                    'content': [{'component': 'VSwitch', 'props': {'model': 'notify', 'label': '开启通知'}}]
                                },
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 3},
                                    'content': [{'component': 'VSwitch', 'props': {'model': 'random_choice', 'label': '随机奖励(如支持)'}}]
                                },
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 3},
                                    'content': [{'component': 'VSwitch', 'props': {'model': 'onlyonce', 'label': '立即运行一次'}}]
                                },
                            ]
                        },
                        {
                            'component': 'VRow',
                            'content': [
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 4},
                                    'content': [{'component': 'VTextField', 'props': {'model': 'member_id', 'label': '用户ID(可选)', 'placeholder': '用于获取用户名/等级/鸡腿'}}]
                                },
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 8},
                                    'content': [{'component': 'VTextField', 'props': {'model': 'user_info_path', 'label': '用户信息API路径(可选)', 'placeholder': '/api/account/getInfo/{member_id}?readme=1'}}]
                                },
                            ]
                        },
                        {
                            'component': 'VRow',
                            'content': [
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12},
                                    'content': [{'component': 'VTextField', 'props': {'model': 'attendance_record_path', 'label': '签到记录API路径(可选)', 'placeholder': '/api/attendance/board?page=1'}}]
                                }
                            ]
                        },
                        {
                            'component': 'VRow',
                            'content': [
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 6},
                                    'content': [{'component': 'VTextField', 'props': {'model': 'site_url', 'label': 'DeepFlood站点URL', 'placeholder': 'https://www.deepflood.com'}}]
                                },
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 6},
                                    'content': [{'component': 'VTextField', 'props': {'model': 'cron', 'label': '定时任务(cron)', 'placeholder': '0 9 * * * (每天9点)'}}]
                                },
                            ]
                        },
                        {
                            'component': 'VRow',
                            'content': [
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12},
                                    'content': [{'component': 'VTextField', 'props': {'model': 'cookie', 'label': '站点Cookie', 'placeholder': '请输入站点Cookie值'}}]
                                }
                            ]
                        },
                        {
                            'component': 'VRow',
                            'content': [
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 6},
                                    'content': [{'component': 'VTextField', 'props': {'model': 'attendance_path', 'label': '签到API路径', 'placeholder': '/api/attendance 或 /attendance.php 等'}}]
                                },
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12, 'md': 6},
                                    'content': [{'component': 'VSelect', 'props': {'model': 'attendance_method', 'label': '签到请求方法', 'items': [{'title': 'POST', 'value': 'POST'}, {'title': 'GET', 'value': 'GET'}]}}]
                                },
                            ]
                        },
                        {
                            'component': 'VRow',
                            'content': [
                                {
                                    'component': 'VCol',
                                    'props': {'cols': 12},
                                    'content': [
                                        {
                                            'component': 'VAlert',
                                            'props': {
                                                'type': 'info',
                                                'variant': 'tonal',
                                                'text': f"依赖状态：curl_cffi={curl_cffi_status}，cloudscraper={cloudscraper_status}。\n\n如 DeepFlood 的接口路径与默认值不同，请按抓包结果配置签到API、用户信息API和签到记录API。"
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                    ]
                }
            ]

            defaults = {
                'enabled': False,
                'notify': False,
                'onlyonce': False,
                'cron': '0 9 * * *',
                'cookie': '',
                'site_url': 'https://www.deepflood.com',
                'random_choice': True,
                'use_proxy': True,
                'max_retries': 3,
                'verify_ssl': False,
                'min_delay': 5,
                'max_delay': 12,
                'history_days': 30,
                'attendance_path': '/api/attendance',
                'attendance_method': 'POST',
                'member_id': '',
                'user_info_path': '/api/account/getInfo/{member_id}?readme=1',
                'attendance_record_path': '/api/attendance/board?page=1',
            }

            return form, defaults

        except Exception as e:
            logger.error(f"[deepfloodsign] get_form error: {str(e)}", exc_info=True)
            # 返回一个错误提示表单，避免 UI 显示“没有可配置项”而无法定位原因
            return [
                {
                    'component': 'VForm',
                    'content': [
                        {
                            'component': 'VAlert',
                            'props': {
                                'type': 'error',
                                'variant': 'tonal',
                                'text': 'deepfloodsign 配置表单渲染失败，请查看 MoviePilot 日志（搜索: [deepfloodsign] get_form）。'
                            }
                        }
                    ]
                }
            ], {}

    def get_page(self) -> List[dict]:
        historys = self.get_data('sign_history') or []
        if not historys:
            return [
                {
                    'component': 'VAlert',
                    'props': {
                        'type': 'info',
                        'variant': 'tonal',
                        'text': '暂无签到记录，请先配置 Cookie 并启用插件',
                        'class': 'mb-2'
                    }
                }
            ]

        historys = sorted(historys, key=lambda x: x.get("date", ""), reverse=True)
        rows = []
        for history in historys:
            status_text = history.get("status", "未知")
            status_color = "success" if ("成功" in status_text or "已签到" in status_text) else "error"
            reward_text = "-"
            if history.get("gain") is not None:
                reward_text = f"{history.get('gain')} 鸡腿"
            rows.append({
                'component': 'tr',
                'content': [
                    {'component': 'td', 'text': history.get("date", "")},
                    {
                        'component': 'td',
                        'content': [
                            {
                                'component': 'VChip',
                                'props': {'color': status_color, 'size': 'small', 'variant': 'outlined'},
                                'text': status_text
                            }
                        ]
                    },
                    {'component': 'td', 'text': reward_text}
                ]
            })

        return [
            {
                'component': 'VCard',
                'props': {'variant': 'outlined', 'class': 'mb-4'},
                'content': [
                    {'component': 'VCardTitle', 'props': {'class': 'text-h6'}, 'text': 'DeepFlood 签到历史'},
                    {
                        'component': 'VCardText',
                        'content': [
                            {
                                'component': 'VTable',
                                'props': {'hover': True, 'density': 'compact'},
                                'content': [
                                    {
                                        'component': 'thead',
                                        'content': [
                                            {
                                                'component': 'tr',
                                                'content': [
                                                    {'component': 'th', 'text': '时间'},
                                                    {'component': 'th', 'text': '状态'},
                                                    {'component': 'th', 'text': '奖励'}
                                                ]
                                            }
                                        ]
                                    },
                                    {'component': 'tbody', 'content': rows}
                                ]
                            }
                        ]
                    }
                ]
            }
        ]

    def get_command(self) -> List[Dict[str, Any]]:
        return []

    def get_api(self) -> List[Dict[str, Any]]:
        return []
